// <auto-generated />
using System;
using KonusarakOgren.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KonusarakOgren.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("KonusarakOgren.Models.Sorular", b =>
                {
                    b.Property<int>("SınavCevapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CevapA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CevapB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CevapC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CevapD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoğruCevap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoruNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SınavID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SınavCevapID");

                    b.HasIndex("SınavID");

                    b.ToTable("Sorular");
                });

            modelBuilder.Entity("KonusarakOgren.Models.Sınav", b =>
                {
                    b.Property<int>("SınavID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslık")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextID")
                        .HasColumnType("TEXT");

                    b.Property<string>("İcerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SınavID");

                    b.ToTable("Sınavlar");
                });

            modelBuilder.Entity("KonusarakOgren.Models.Sorular", b =>
                {
                    b.HasOne("KonusarakOgren.Models.Sınav", "Sınav")
                        .WithMany("Sorulars")
                        .HasForeignKey("SınavID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sınav");
                });

            modelBuilder.Entity("KonusarakOgren.Models.Sınav", b =>
                {
                    b.Navigation("Sorulars");
                });
#pragma warning restore 612, 618
        }
    }
}
